### PR TITLE
Added IDs in all models

### LINKED ISSUE #120: Models should have the attribute 'id'
### Request Type
Bug

### Problem Description
Models should have the attribute 'id' since it's an attribute of the real entity.
No model defined in models.py has this attribute
Created models from json should have id too.

### PR DESCRIPTION
**Pull request by mgabriel-silva**
Added IDs in all models
Fixes #120

### CODE REVIEW

**Comment by nadouani** [comment]
We need to revert this issue since the create APIs don't allow providing ID for entities to be created.

**Comment by nadouani** [comment]
Or a better idea, remove the `id` during the creation process. I'll update the `jsonify` function to allow an `exclude` arg where we can specify fields to exclude

**Comment by mgabriel-silva** [comment]
It's better to let that id there. Everytime we do an update, we have to manually insert the id.
The update method requires an id, but the models didn't had it.

**Comment by nadouani** [comment]
Yes, the change I made is to exclude the `id` from creation calls

**Pull request merged**
