### PR TITLE
Feature: Support proxies and client cert settings for authentication

### PR DESCRIPTION
**Pull request by LetMeR00t**
It was not possible to use a client certificate nor proxy settings.
Now, we can use them and they are not mandatory

### CODE REVIEW

**Comment by Kamforka** [comment]
We don't use setup.py anymore, the project has switched to pyproject.toml, please fix that

**Comment by LetMeR00t** [comment]
Hello,

Is that better ?

Thank you

**Comment by Kamforka** [comment]
> Hello,
> 
> Is that better ?
> 
> Thank you

Yep, looks good. Could you test it somehow?

**Comment by LetMeR00t** [comment]
@Kamforka, I can work on something but no sure it will be easy to setup honestly.
I've added the support for catalog and patterns, without any test for now.
Please let me know if some changes need to be done and then I'll work on tests for this.
Thank you

**Comment by LetMeR00t** [comment]
I'll review those changes in dedicated MR

**Pull request closed without merging**
