### PR TITLE
Add observableType endpoints

### PR DESCRIPTION
**Pull request by Black-Pearl25**
- Added an endpoint for observable types, the script contains four functions : create, get, delete and find. It passed the tests.

### CODE REVIEW

**Comment by Kamforka** [comment]
Thanks for the PR! Gonna review tomorrow!

**Comment by Kamforka** [comment]
CI jobs didn't trigger, can you please add the below to `.github/workflows/ci.yml`:

```yaml
on: [push, pull_request]
```

**Comment by Black-Pearl25** [comment]
Done.

**Review by Kamforka — CHANGES_REQUESTED** [review]

**Comment by Kamforka** [comment]
> Done.

I'd also recommend you to set up [black](https://github.com/psf/black) locally to aid you with formatting!

**Comment by Black-Pearl25** [comment]
Done, and thanks for the suggestion, i'll do that.

**Review by Kamforka — APPROVED** [review]
Just resolve the workflow conflict and it is good to go!

**Comment by Black-Pearl25** [comment]
Done!

**Pull request merged**
