### PR TITLE
Feature/support persistence for licence pytest

### PR DESCRIPTION
**Pull request by LetMeR00t**
Hello,
Following a wish to open the development and especially tests using development licence, I propose to support persistence for pytest using a docker compose file
Keep me posted.

### CODE REVIEW

**Comment by Kamforka** [comment]
Can you convert this one into an issue rather than a PR?

**Comment by LetMeR00t** [comment]
Yes of course but does it means that you want to build/make it yourself and avoid this PR?
Thank you

**Comment by Kamforka** [comment]
We can keep the PR too, but the natural flow is to start with an issue if you have a feature request. So then we can track the conversation there.
Also this particular topic is an overarching one, as we cannot come up with our own dev license programme but we need StrangeBee's support to make that happen.

**Comment by LetMeR00t** [comment]
You're right about the workflow, I'm sorry :)
I've created the corresponding issue here: #292

Thank you

**Comment by LetMeR00t** [comment]
By the way @Kamforka , do you need assistance to solve the pytest issues if there are any based on the fact that I'm running on an independant platform without any data (and so perfect to solve the issues if you have persistent data on your side).
Let me know if I can help you.

**Pull request closed without merging**
