### PR TITLE
Allow params and query in get_task_logs()

### PR DESCRIPTION
**Pull request by jnahorny**
Make get_task_logs() use 'api/case/task/log/_search/' API endpoint. This allows specifying params and also query. Current implementation of this method only returns 10 case task logs at max. I believe this addresses issue #160

### CODE REVIEW

**Comment by jnahorny** [comment]
@nadouani I see 1.7.2 has been tagged last week. When do you estimate 1.8.0 to happen? I'm asking because I need this functionality, and if that's a 'reasonable wait', I'll just wait. But if that's multiple weeks, I'll have to write some work around code for now. Thank you!

**Comment by nadouani** [comment]
Hello @jnahorny I don't know if you are using TheHive4py, could you update your PR to be up to date so I can merge it? Thanks

**Comment by jnahorny** [comment]
> Hello @jnahorny I don't know if you are using TheHive4py, could you update your PR to be up to date so I can merge it? Thanks

Hi @nadouani 
Yes, I am using TheHive4py all the time. I've rebased my PR on the top of the current state of `1.x` branch. I'm not sure why here in the PR it shows 7 files modified :/
When I visit https://github.com/TheHive-Project/TheHive4py/compare/1.x...jnahorny:allow-params-and-query-in-get_task_logs
it correctly shows just *one* files as modified, with only my changes.
Git is so simple, but sometimes I can't figure out what is it trying to tell me :)

**Comment by jnahorny** [comment]
If I did something incorrectly, I'll try to fix it :/

**Comment by jnahorny** [comment]
@nadouani sorry, but I had to delete this PR. I've messed something up, and wasn't able to fix it.
I've created a new PR, number 200 (https://github.com/TheHive-Project/TheHive4py/pull/200). This one looks properly, it only changes one file.
Again, I'm very sorry for that!

**Pull request closed without merging**
