### PR TITLE
#352 - Add deprecation wraning to the 1.x codebase

### PR DESCRIPTION
**Pull request by Kamforka**
As per #352

### CODE REVIEW

**Comment by Kamforka** [comment]
It will produce warnings like the belows:

```python
>>> import thehive4py
<stdin>:1: DeprecationWarning: thehive4py v1.x is not maintained anymore as TheHive v3 and v4 are end of life. If you are using TheHive v5 please consider switching to thehive4py v2.x (https://github.com/TheHive-Project/TheHive4py)!
```

or

```python
>>> from thehive4py.models import Version
<stdin>:1: DeprecationWarning: thehive4py v1.x is not maintained anymore as TheHive v3 and v4 are end of life. If you are using TheHive v5 please consider switching to thehive4py v2.x (https://github.com/TheHive-Project/TheHive4py)!
```

**Comment by nadouani** [comment]
@Kamforka I believe this might break scripts that are supposed to just print a json to the console. Thoughts?

**Comment by Kamforka** [comment]
> @Kamforka I believe this might break scripts that are supposed to just print a json to the console. Thoughts?

@nadouani yes, free text parsers would be affected by this change. But I'd consider those as do-it-for-your-own-risk solutions.

Nevertheless, do you think we should drop this PR then?

**Comment by nadouani** [comment]
I would say GO, users can always downgrade to 1.8.1

**Pull request merged**
