### PR TITLE
Changed update_case method

### PR DESCRIPTION
**Pull request by npratley**
To address #57 the update_case method now takes attributes and their new values as parameters, rather than updating the full set of case attributes each time.

### CODE REVIEW

**Comment by Rolinh** [comment]
It *would* break scripts, this is for certain.
Yet, I think this is an improvement. To avoid breakage, one could add this as another method at the expense of cluttering the client's code.
If this change is accepted as is, for the sake of consistency, I think that the `update_alert` method shall be updated as well.

**Comment by nadouani** [comment]
I agree. We just need to communicate about it then. 

@npratley can you please add the same changes to `update_alert`?

Thanks

**Comment by npratley** [comment]
Yes it is definitely a breaking change. Happy to update update_alert as well.

**Comment by nadouani** [comment]
Closing this as obsolete

**Pull request closed without merging**
