### PR TITLE
Implement some more functions

### PR DESCRIPTION
**Pull request by jojoob**
This pull requests adds the following functions:
* **get_case_task(taskId)** retrieve a single task by its id
* **get_task_log(attributes)** retrieve a single task log by its id
* **delete_case(case_id, force=False)** soft/hard delete a case
* **health()** retrieve health info

### CODE REVIEW

**Comment by nadouani** [comment]
Hello @jojoob, Thanks for the contributions. 

TheHive4py is beeing completely rewritten (take a look to `feature/reboot` branch).

I could accept these contributions, but once version 2.0 will be released, I think they will be sadly obsolete :(

**Comment by nadouani** [comment]
For info: this is the full list of methods that will be provided:

https://github.com/TheHive-Project/TheHive4py/blob/feature/reboot/docs/usage.md

If you have suggestions, about methods that can be added, then please shoot

**Comment by jojoob** [comment]
@nadouani I know about the ongoing rewrite of TheHive4py and I'm looking glad and impatient forward to its release. ;) Do you have already a planned release date?
Please let me know if you need any help on this.

I extended the current API client because I needed it for a current project I'm working on. So I just wanted to share my work. It's up to you if you want to merge this. I've also two other branches extending the current API...

**Comment by nadouani** [comment]
That's cool thanks for the contributions! We will for sure continue maintaining version < 2.0 until everybody move from it.

If you have time, can you give some feedback about 2.0? It's almost release ready, but the documentation is not :(

**Comment by jojoob** [comment]
Yes, I'll look into 2.0. As soon as I've some time for this I will begin rewriting my application to use TheHive4py 2.0 and post my feedback.

**Comment by jojoob** [comment]
I changed one commit and rebased the branch because of duplicate find_tasks function.

**Comment by nadouani** [comment]
This PR will be merged into `1.x` branch that will be the master branch of version < 2

**Pull request merged**
