### PR TITLE
Importing requests module

### PR DESCRIPTION
**Pull request by gaglimax**
Importing requests module to fix the error :

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/thehive4py/auth.py", line 24, in __call__
    req.headers['Authorization'] = requests.auth._basic_auth_str(self.username, self.password)
NameError: name 'requests' is not defined
```

### CODE REVIEW

**Comment by nadouani** [comment]
Hello, I'm going to fix this because in fact I've made something wrong, not just here but on the constructor of TheHiveApi.

**Comment by gaglimax** [comment]
Sounds great thanks !

**Comment by nadouani** [comment]
@gaglimax  I made a 1.7.2 release. Can you please check it? Thanks

**Comment by gaglimax** [comment]
Yes it works fine now 👍 
Thanks a lot @nadouani !

**Pull request merged**
